import React, { useState, useEffect } from 'react';
import { 
  FileText, 
  Download, 
  Printer, 
  Sparkles, 
  CheckCircle2, 
  Calendar, 
  ShieldCheck, 
  Layers, 
  Clock, 
  Activity,
  Plus
} from 'lucide-react';
import { socStore } from '../../services/storage';
import { SOCReport } from '../../types/soc';

interface SOCReportingProps {
  onAskAI: (prompt: string) => void;
}

export const SOCReporting: React.FC<SOCReportingProps> = ({ onAskAI }) => {
  const [reports, setReports] = useState<SOCReport[]>(socStore.getReports());
  const [activeReport, setActiveReport] = useState<SOCReport | null>(null);
  const [isGenerating, setIsGenerating] = useState(false);

  useEffect(() => {
    const unsub = socStore.subscribe(() => {
      const current = socStore.getReports();
      setReports(current);
      if (!activeReport && current.length > 0) {
        setActiveReport(current[0]);
      }
    });
    return unsub;
  }, []);

  useEffect(() => {
    if (reports.length > 0 && !activeReport) {
      setActiveReport(reports[0]);
    }
  }, [reports]);

  const handleGenerateReport = (type: SOCReport['type']) => {
    setIsGenerating(true);
    setTimeout(() => {
      const activeTenant = socStore.getActiveTenant();
      const newReport: SOCReport = {
        id: `REP-${Date.now()}`,
        tenantId: activeTenant.id,
        title: type === 'DAILY_SUMMARY' ? `Daily SOC Operational Briefing — ${new Date().toLocaleDateString()}` : `Technical Post-Mortem & Incident Closure — ${new Date().toLocaleDateString()}`,
        type,
        createdAt: new Date().toISOString().replace('T', ' ').substring(0, 19),
        generatedBy: 'Vichhai AI (Reporting Agent)',
        summary: `Autonomous SOC report for ${activeTenant.name}. 1,245 events analyzed with autonomous MTTR calculation.`,
        stats: {
          totalAlerts: 1245,
          highSeverityAlerts: 38,
          incidentsInvestigated: 7,
          confirmedThreats: 2,
          isolatedEndpoints: 1,
          mttrMinutes: 14.5,
          blockedIocs: 24,
        },
        contentMarkdown: `# Automated SOC Report
**Tenant:** ${activeTenant.name} (${activeTenant.code})
**Date:** ${new Date().toLocaleDateString()}
**Generated by:** Vichhai AI Autonomous Reporting Agent

---

## 1. Executive Summary
During this reporting period, Vichhai AI ingested **1,245 alerts** and correlated **7 multi-stage incidents**. 

### Operational Telemetry
* **Total Alerts Ingested:** 1,245
* **High Severity:** 38
* **False Positives Suppressed:** 942 (75.6%)
* **Mean Time to Detect (MTTD):** 1.8 mins
* **Mean Time to Respond (MTTR):** 14.5 mins

---

## 2. Critical Threat Containment
* **Endpoint:** PC-NITH (192.168.10.45)
* **Threat Attribution:** APT29 (Cozy Bear) / Cobalt Strike
* **Action:** Host Isolation & Perimeter Firewall Drop
* **Status:** Remediated via Shuffle SOAR.`,
      };
      socStore.addReport(newReport);
      setActiveReport(newReport);
      setIsGenerating(false);
    }, 800);
  };

  const handlePrint = () => {
    window.print();
  };

  const handleDownloadMarkdown = () => {
    if (!activeReport) return;
    const blob = new Blob([activeReport.contentMarkdown], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${activeReport.title.replace(/[^a-zA-Z0-9]/g, '_')}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="p-6 space-y-6 max-w-7xl mx-auto">
      {/* Top Banner */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <h1 className="text-xl font-black text-white flex items-center space-x-2">
            <FileText className="w-6 h-6 text-emerald-400" />
            <span>Automated SOC Reporting & Compliance</span>
          </h1>
          <p className="text-xs text-slate-400 mt-0.5">
            Daily SOC Briefings, Technical Deep-Dives, Post-Mortems & Compliance Artifacts
          </p>
        </div>

        {/* Generate Report Buttons */}
        <div className="flex items-center space-x-2">
          <button
            onClick={() => handleGenerateReport('DAILY_SUMMARY')}
            disabled={isGenerating}
            className="px-3.5 py-2 rounded-xl bg-gradient-to-r from-emerald-600 to-teal-600 hover:from-emerald-500 text-white font-bold text-xs flex items-center space-x-1.5 shadow-lg shadow-emerald-950/40"
          >
            <Sparkles className="w-3.5 h-3.5" />
            <span>Generate Daily Summary</span>
          </button>

          <button
            onClick={() => handleGenerateReport('POST_MORTEM')}
            disabled={isGenerating}
            className="px-3.5 py-2 rounded-xl bg-[#121c2e] hover:bg-[#1a2842] text-cyan-300 border border-cyan-500/30 text-xs font-semibold flex items-center space-x-1.5"
          >
            <Plus className="w-3.5 h-3.5" />
            <span>Technical Post-Mortem</span>
          </button>
        </div>
      </div>

      {/* Main Grid: Left Report Catalog, Right Rich Report Viewer */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        {/* Left: Report Catalog */}
        <div className="lg:col-span-4 space-y-3">
          <div className="text-xs font-bold text-slate-400 uppercase tracking-wider">
            Generated Reports ({reports.length})
          </div>

          <div className="space-y-2.5 max-h-[640px] overflow-y-auto pr-1">
            {reports.map((rep) => {
              const isSelected = activeReport?.id === rep.id;
              return (
                <div
                  key={rep.id}
                  onClick={() => setActiveReport(rep)}
                  className={`p-3.5 rounded-2xl border transition-all cursor-pointer ${
                    isSelected
                      ? 'bg-[#12222a] border-emerald-500 shadow-lg shadow-emerald-950/60 ring-1 ring-emerald-500/40'
                      : 'bg-[#0e1626] border-[#1e2d4d] hover:border-slate-500'
                  }`}
                >
                  <div className="flex items-center space-x-2">
                    <span className="px-2 py-0.2 rounded bg-emerald-500/20 text-emerald-300 font-mono text-[9px] font-bold uppercase">
                      {rep.type}
                    </span>
                    <span className="text-[10px] text-slate-400 font-mono">{rep.id}</span>
                  </div>

                  <h3 className="text-xs font-bold text-white mt-1.5 line-clamp-2">
                    {rep.title}
                  </h3>

                  <p className="text-[11px] text-slate-400 mt-1 line-clamp-2">
                    {rep.summary}
                  </p>

                  <div className="mt-2.5 pt-2 border-t border-[#1e2d4d]/60 flex items-center justify-between text-[10px] text-slate-400">
                    <span>{rep.createdAt.split(' ')[0]}</span>
                    <span className="text-emerald-400 font-semibold">{rep.generatedBy.split('(')[0]}</span>
                  </div>
                </div>
              );
            })}
          </div>
        </div>

        {/* Right: Rich Report Document Viewer */}
        <div className="lg:col-span-8">
          {activeReport ? (
            <div className="bg-[#0b1220] border border-[#1b2742] rounded-2xl p-6 shadow-2xl space-y-6">
              {/* Document Action Toolbar */}
              <div className="flex items-center justify-between border-b border-[#1b2742] pb-4">
                <div>
                  <span className="text-[10px] font-mono px-2 py-0.5 rounded bg-emerald-500/20 text-emerald-300 font-bold uppercase">
                    {activeReport.type}
                  </span>
                  <h2 className="text-base font-bold text-white mt-1">
                    {activeReport.title}
                  </h2>
                  <div className="text-[11px] text-slate-400 mt-0.5">
                    Generated: {activeReport.createdAt} by {activeReport.generatedBy}
                  </div>
                </div>

                <div className="flex items-center space-x-2">
                  <button
                    onClick={handleDownloadMarkdown}
                    className="p-2 rounded-xl bg-[#121c2e] hover:bg-[#1a2842] text-slate-200 border border-[#1e2d4d] text-xs font-medium flex items-center space-x-1.5 transition-all"
                    title="Download Markdown"
                  >
                    <Download className="w-3.5 h-3.5 text-cyan-400" />
                    <span>Markdown</span>
                  </button>

                  <button
                    onClick={handlePrint}
                    className="p-2 rounded-xl bg-[#121c2e] hover:bg-[#1a2842] text-slate-200 border border-[#1e2d4d] text-xs font-medium flex items-center space-x-1.5 transition-all"
                    title="Print / Save PDF"
                  >
                    <Printer className="w-3.5 h-3.5 text-emerald-400" />
                    <span>Print PDF</span>
                  </button>
                </div>
              </div>

              {/* Exact Prompt Example Executive Stats Box */}
              <div className="bg-[#070b14] p-4 rounded-xl border border-emerald-500/40 space-y-3 font-mono text-xs">
                <div className="text-emerald-400 font-bold text-[11px] uppercase tracking-wider">
                  📊 Daily SOC Operational Metrics
                </div>
                <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 text-slate-300">
                  <div className="p-2 bg-[#0e172a] rounded-lg border border-[#1e2d4d]">
                    <div className="text-slate-400 text-[10px]">Alerts Received</div>
                    <div className="text-base font-black text-white">{activeReport.stats.totalAlerts.toLocaleString()}</div>
                  </div>
                  <div className="p-2 bg-[#0e172a] rounded-lg border border-[#1e2d4d]">
                    <div className="text-slate-400 text-[10px]">High / Critical</div>
                    <div className="text-base font-black text-rose-400">{activeReport.stats.highSeverityAlerts}</div>
                  </div>
                  <div className="p-2 bg-[#0e172a] rounded-lg border border-[#1e2d4d]">
                    <div className="text-slate-400 text-[10px]">Incidents Investigated</div>
                    <div className="text-base font-black text-cyan-300">{activeReport.stats.incidentsInvestigated}</div>
                  </div>
                  <div className="p-2 bg-[#0e172a] rounded-lg border border-[#1e2d4d]">
                    <div className="text-slate-400 text-[10px]">Isolated Endpoints</div>
                    <div className="text-base font-black text-amber-300">{activeReport.stats.isolatedEndpoints}</div>
                  </div>
                </div>
              </div>

              {/* Markdown Rendered Content */}
              <div className="bg-[#080d17] p-5 rounded-xl border border-[#1e2d4d] font-sans text-xs text-slate-200 leading-relaxed whitespace-pre-wrap select-text">
                {activeReport.contentMarkdown}
              </div>
            </div>
          ) : (
            <div className="bg-[#0b1220] border border-[#1b2742] rounded-2xl p-12 text-center text-slate-400">
              Select a report to view and export.
            </div>
          )}
        </div>
      </div>
    </div>
  );
};
